@startuml
class ClassAnalyzer {
  + analyze() : UMLClass
  - getVisibility() : String
}
class FileAnalyzer {
  + scan() : List<File>
}
class RelationShipAnalyzer {
  - : AssociationDetector
  - : InheritanceDetector
  - : ImplementationDetector
  - : DependencyDetector
  - : CompositionDetector
  + analyze() : List<UMLRelationship>
}
class AssociationDetector {
  + detect() : List<UMLRelationship>
}
class CompositionDetector {
  + detect() : List<UMLRelationship>
}
class DependencyDetector {
  + detect() : List<UMLRelationship>
}
class ImplementationDetector {
  + detect() : List<UMLRelationship>
}
class InheritanceDetector {
  + detect() : List<UMLRelationship>
}
class UMLGeneratorFactory {
  + createRelationshipAnalyzer() : RelationShipAnalyzer
  + createUMLGenerator() : UMLGenerator
}
class PdfGenerator {
  + printDiagram() : void
}
class PlainUmlGenerator {
  + generate() : String
}
class UMLCodeGenerator {
  + saveUMLCode() : void
}
class UMLClass {
  - : String
  - : List<UMLField>
  - : List<UMLMethod>
  - : List<String>
  - : List<String>
  - : List<String>
  - : List<String>
  + getName() : String
  + setName() : void
  + getFields() : List<UMLField>
  + setFields() : void
  + getMethods() : List<UMLMethod>
  + setMethods() : void
  + getInterfaces() : List<String>
  + setInterfaces() : void
  + getParentClass() : List<String>
  + setParentClass() : void
  + getDependencies() : List<String>
  + setDependencies() : void
  + getCreatedObjects() : List<String>
  + setCreatedObjects() : void
}
class UMLField {
  - : String
  - : String
  - : String
  + toString() : String
  + getName() : String
  + setName() : void
  + getType() : String
  + setType() : void
  + getVisibility() : String
  + setVisibility() : void
}
class UMLMethod {
  - : String
  - : String
  - : String
  - : List<String>
  + getName() : String
  + setName() : void
  + getReturnType() : String
  + setReturnType() : void
  + getVisibility() : String
  + setVisibility() : void
  + getParameter() : List<String>
  + setParameter() : void
}
class UMLRelationship {
  - : String
  - : String
  - : RelationshipType
  + toString() : String
  + getSource() : String
  + setSource() : void
  + getTarget() : String
  + setTarget() : void
  + getType() : RelationshipType
  + setType() : void
}
class UMLGenerator {
  - : FileAnalyzer
  - : PlainUmlGenerator
  - : PdfGenerator
  - : ClassAnalyzer
  - : RelationShipAnalyzer
  - : UMLCodeGenerator
  + generate() : void
}
class UmlCommands {
  + main() : void
}
class RelationshipUtils {
  + generateRelationshipArrow() : String
}
RelationShipAnalyzer -- AssociationDetector
RelationShipAnalyzer -- InheritanceDetector
UMLGenerator -- FileAnalyzer
RelationShipAnalyzer -- CompositionDetector
UMLGenerator -- PlainUmlGenerator
UMLGenerator -- UMLCodeGenerator
UMLGenerator -- PdfGenerator
UMLGenerator -- RelationShipAnalyzer
RelationShipAnalyzer -- DependencyDetector
RelationShipAnalyzer -- ImplementationDetector
UMLGenerator -- ClassAnalyzer
@enduml
